### ISSUE TITLE
NendModule.hとNendInterstitialModule.hを一緒にincludeするとコンパイルエラー

### ISSUE THREAD

**Issue by yokochi** [fan-ADN/nendSDK-cocos2d-x#1]
```
#include "NendModule.h"
#include "NendInterstitialModule.h"
```

上記を同時に読み込むと以下のエラーになります。
NendInterstitialModule.h:54:5: Redefinition of enumerator 'CLICK_INFORMATION'

CLICK_INFORMATIONの名前が同じだからでしょうか

SDK Versionがちょっとわからないのですが、管理画面で2016/08/04 (木)リリースとなっているものです

**Comment by fan-t-fukuoka** [comment]
@yokochi 様
お問い合わせ頂きありがとうございます。
ファンコミュニケーションズの福岡と申します。

> 上記を同時に読み込むと以下のエラーになります。
> NendInterstitialModule.h:54:5: Redefinition of enumerator 'CLICK_INFORMATION'
> CLICK_INFORMATIONの名前が同じだからでしょうか

こちらの件は、名前が同じのため重複定義でエラーとなっておりました。
誠に申し訳ございませんが、
`NendModule.h`または`NendInterstitialModule.h`で定義しているどちらかの`CLICK_INFORMATION`の名前を`CLICK_INFORMATION_BANNER`や`CLICK_INFORMATION_INTERSTITIAL`のように変更して頂き、EventDispatcher通知の受け取りを実装している箇所にも、その変更を適用して頂くことでエラーの回避が可能でございます。

こちらの問題は次回のモジュールアップデートで修正させて頂きますので、
それまでは上記の回避方法で対処をお願い致します。

**Comment by yokochi** [comment]
了解しました。よろしくお願いします

**Comment by fan-t-fukuoka** [comment]
@yokochi 様
お手数お掛けして申し訳ございませんが、
今後とも宜しくお願い致します。
